name = "teach-anything"
main = ".open-next/worker.js"
compatibility_date = "2026-02-28"
compatibility_flags = ["nodejs_compat"]

[vars]
OPENAI_BASE_URL = "api.openai.com"
OPENAI_MODEL = "gpt-3.5-turbo-0125"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
